package carScraperServer.scrapeEngine;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class AutotraderSearchHelper {
    private static final Map<String, String> makesMap = new HashMap<>();
    private static final Map<String, String> modelsMap = new HashMap<>();

    static {

        makesMap.put("any make", "");
        makesMap.put("acura", "ACURA");
        makesMap.put("alfa romeo", "ALFA");
        makesMap.put("amc", "AMC");
        makesMap.put("aston martin", "ASTON");
        makesMap.put("audi", "AUDI");
        makesMap.put("bentley", "BENTL");
        makesMap.put("bmw", "BMW");
        makesMap.put("buick", "BUICK");
        makesMap.put("cadillac", "CAD");
        makesMap.put("chevrolet", "CHEV");
        makesMap.put("chrysler", "CHRY");
        makesMap.put("daewoo", "DAEW");
        makesMap.put("datsun", "DATSUN");
        makesMap.put("delorean", "DELOREAN");
        makesMap.put("dodge", "DODGE");
        makesMap.put("eagle", "EAGLE");
        makesMap.put("ferrari", "FER");
        makesMap.put("fiat", "FIAT");
        makesMap.put("fisker", "FISK");
        makesMap.put("ford", "FORD");
        makesMap.put("freightliner", "FREIGHT");
        makesMap.put("geo", "GEO");
        makesMap.put("gmc", "GMC");
        makesMap.put("honda", "HONDA");
        makesMap.put("hummer", "AMGEN");
        makesMap.put("hyundai", "HYUND");
        makesMap.put("infiniti", "INFIN");
        makesMap.put("isuzu", "ISU");
        makesMap.put("jaguar", "JAG");
        makesMap.put("jeep", "JEEP");
        makesMap.put("kia", "KIA");
        makesMap.put("lamborghini", "LAM");
        makesMap.put("land rover", "ROV");
        makesMap.put("lexus", "LEXUS");
        makesMap.put("lincoln", "LINC");
        makesMap.put("lotus", "LOTUS");
        makesMap.put("maserati", "MAS");
        makesMap.put("maybach", "MAYBACH");
        makesMap.put("mazda", "MAZDA");
        makesMap.put("mclaren", "MCLAREN");
        makesMap.put("mercedes-benz", "MB");
        makesMap.put("mercury", "MERC");
        makesMap.put("mini", "MINI");
        makesMap.put("mitsubishi", "MIT");
        makesMap.put("nissan", "NISSAN");
        makesMap.put("oldsmobile", "OLDS");
        makesMap.put("plymouth", "PLYM");
        makesMap.put("pontiac", "PONT");
        makesMap.put("porsche", "POR");
        makesMap.put("ram", "RAM");
        makesMap.put("rolls-royce", "RR");
        makesMap.put("saab", "SAAB");
        makesMap.put("saturn", "SATURN");
        makesMap.put("scion", "SCION");
        makesMap.put("smart", "SMART");
        makesMap.put("srt", "SRT");
        makesMap.put("subaru", "SUB");
        makesMap.put("suzuki", "SUZUKI");
        makesMap.put("tesla", "TESLA");
        makesMap.put("toyota", "TOYOTA");
        makesMap.put("volkswagen", "VOLKS");
        makesMap.put("volvo", "VOLVO");
        makesMap.put("yugo", "YUGO");





        modelsMap.put("any model", "");
        modelsMap.put("cl", "ACUCL");
        modelsMap.put("ilx", "ILX");
        modelsMap.put("integra", "INTEG");
        modelsMap.put("legend", "LEGEND");
        modelsMap.put("mdx", "MDX");
        modelsMap.put("nsx", "NSX");
        modelsMap.put("rdx", "RDX");
        modelsMap.put("rl", "RL");
        modelsMap.put("rlx", "RLX");
        modelsMap.put("rsx", "RSX");
        modelsMap.put("slx", "SLX");
        modelsMap.put("tl", "TL");
        modelsMap.put("tlx", "ACUTLX");
        modelsMap.put("tsx", "TSX");
        modelsMap.put("vigor", "VIGOR");
        modelsMap.put("zdx", "ZDX");
        modelsMap.put("other acura models", "ACUOTH");
        modelsMap.put("164", "ALFA164");
        modelsMap.put("4c", "ALFA4C");
        modelsMap.put("8c competizione", "ALFA8C");
        modelsMap.put("gtv-6", "ALFAGT");
        modelsMap.put("milano", "MIL");
        modelsMap.put("spider", "SPID");
        modelsMap.put("other alfa romeo models", "ALFAOTH");
        modelsMap.put("alliance", "AMCALLIAN");
        modelsMap.put("concord", "CON");
        modelsMap.put("eagle", "EAGLE");
        modelsMap.put("encore", "AMCENC");
        modelsMap.put("spirit", "AMCSPIRIT");
        modelsMap.put("other amc models", "AMCOTH");
        modelsMap.put("db7", "DB7");
        modelsMap.put("db9", "DB9");
        modelsMap.put("dbs", "DBS");
        modelsMap.put("lagonda", "LAGONDA");
        modelsMap.put("rapide", "RAPIDE");
        modelsMap.put("rapide s", "ASTRAPIDES");
        modelsMap.put("v12 vantage", "V12VANT");
        modelsMap.put("v8 vantage", "VANTAGE");
        modelsMap.put("vanquish", "VANQUISH");
        modelsMap.put("virage", "VIRAGE");
        modelsMap.put("other aston martin models", "ASTOTH");
        modelsMap.put("100", "AUDI100");
        modelsMap.put("200", "AUDI200");
        modelsMap.put("4000", "4000");
        modelsMap.put("5000", "5000");
        modelsMap.put("80", "80");
        modelsMap.put("90", "90");
        modelsMap.put("a3", "A3");
        modelsMap.put("a4", "A4");
        modelsMap.put("a5", "A5");
        modelsMap.put("a6", "A6");
        modelsMap.put("a7", "A7");
        modelsMap.put("a8", "A8");
        modelsMap.put("allroad", "ALLRDQUA");
        modelsMap.put("cabriolet", "AUDICABRI");
        modelsMap.put("coupe", "AUDICOUPE");
        modelsMap.put("q3", "Q3");
        modelsMap.put("q5", "Q5");
        modelsMap.put("q7", "Q7");
        modelsMap.put("quattro", "QUATTR");
        modelsMap.put("r8", "R8");
        modelsMap.put("rs 4", "RS4");
        modelsMap.put("rs 5", "RS5");
        modelsMap.put("rs 6", "RS6");
        modelsMap.put("rs 7", "AUDIRS7");
        modelsMap.put("s3", "AUDS3");
        modelsMap.put("s4", "S4");
        modelsMap.put("s5", "S5");
        modelsMap.put("s6", "S6");
        modelsMap.put("s7", "S7");
        modelsMap.put("s8", "S8");
        modelsMap.put("sq5", "AUDISQ5");
        modelsMap.put("tt", "TT");
        modelsMap.put("tt rs", "TTRS");
        modelsMap.put("tts", "TTS");
        modelsMap.put("v8 quattro", "V8");
        modelsMap.put("other audi models", "AUDOTH");
        modelsMap.put("arnage", "ARNAGE");
        modelsMap.put("azure", "AZURE");
        modelsMap.put("brooklands", "BROOKLANDS");
        modelsMap.put("continental", "BENCONT");
        modelsMap.put("eight", "BENEIGHT");
        modelsMap.put("flying spur", "BENFLYSPUR");
        modelsMap.put("mulsanne", "BENMUL");
        modelsMap.put("turbo r", "BENTURBO");
        modelsMap.put("other bentley models", "BENOTH");
        modelsMap.put("1 series m", "1SERIESM");
        modelsMap.put("1 series (3)", "1_SERIES");
        modelsMap.put("128i", "128I");
        modelsMap.put("135i", "135I");
        modelsMap.put("135is", "135IS");
        modelsMap.put("2 series (4)", "2_SERIES");
        modelsMap.put("228i", "BMW228I");
        modelsMap.put("228i xdrive", "BMW228IXD");
        modelsMap.put("m235i", "BMWM235I");
        modelsMap.put("m235i xdrive", "BMWM235IXD");
        modelsMap.put("3 series (36)", "3_SERIES");
        modelsMap.put("318i", "318I");
        modelsMap.put("318is", "318IS");
        modelsMap.put("318ti", "318TI");
        modelsMap.put("320i", "320I");
        modelsMap.put("320i xdrive", "320IXD");
        modelsMap.put("323ci", "323CI");
        modelsMap.put("323i", "323I");
        modelsMap.put("323is", "323IS");
        modelsMap.put("325", "BMW325");
        modelsMap.put("325ci", "325CI");
        modelsMap.put("325e", "325E");
        modelsMap.put("325es", "325ES");
        modelsMap.put("325i", "325I");
        modelsMap.put("325ix", "325IX");
        modelsMap.put("325is", "325IS");
        modelsMap.put("325xi", "325XI");
        modelsMap.put("328ci", "328CI");
        modelsMap.put("328d", "BMW328D");
        modelsMap.put("328d xdrive", "BMW328DXD");
        modelsMap.put("328i", "328I");
        modelsMap.put("328i gran turismo xdrive", "BMW328GTXD");
        modelsMap.put("328i xdrive", "328IXD");
        modelsMap.put("328is", "328IS");
        modelsMap.put("328xi", "328XI");
        modelsMap.put("330ci", "330CI");
        modelsMap.put("330i", "330I");
        modelsMap.put("330xi", "330XI");
        modelsMap.put("335d", "335D");
        modelsMap.put("335i", "335I");
        modelsMap.put("335i gran turismo xdrive", "BMW335GTXD");
        modelsMap.put("335i xdrive", "335IXD");
        modelsMap.put("335is", "335IS");
        modelsMap.put("335xi", "335XI");
        modelsMap.put("340i", "BMW340I");
        modelsMap.put("340i xdrive", "BMW340IXD");
        modelsMap.put("activehybrid 3", "ACTIVE3");
        modelsMap.put("4 series (8)", "4_SERIES");
        modelsMap.put("428i", "BMW428I");
        modelsMap.put("428i gran coupe", "BMW428GC");
        modelsMap.put("428i gran coupe xdrive", "BMW428GCXD");
        modelsMap.put("428i xdrive", "BMW428IXD");
        modelsMap.put("435i", "BMW435I");
        modelsMap.put("435i gran coupe", "BMW435GC");
        modelsMap.put("435i gran coupe xdrive", "BMW435GCXD");
        modelsMap.put("435i xdrive", "BMW435IXD");
        modelsMap.put("5 series (24)", "5_SERIES");
        modelsMap.put("524td", "524TD");
        modelsMap.put("525i", "525I");
        modelsMap.put("525xi", "525XI");
        modelsMap.put("528e", "528E");
        modelsMap.put("528i", "528I");
        modelsMap.put("528i xdrive", "528IXD");
        modelsMap.put("528xi", "528XI");
        modelsMap.put("530i", "530I");
        modelsMap.put("530xi", "530XI");
        modelsMap.put("533i", "533I");
        modelsMap.put("535d", "BMW535D");
        modelsMap.put("535d xdrive", "BMW535DXD");
        modelsMap.put("535i", "535I");
        modelsMap.put("535i gran turismo", "535IGT");
        modelsMap.put("535i gran turismo xdrive", "535IGTXD");
        modelsMap.put("535i xdrive", "535IXD");
        modelsMap.put("535xi", "535XI");
        modelsMap.put("540i", "540I");
        modelsMap.put("545i", "545I");
        modelsMap.put("550i", "550I");
        modelsMap.put("550i gran turismo", "550IGT");
        modelsMap.put("550i gran turismo xdrive", "550IGTXD");
        modelsMap.put("550i xdrive", "550IXD");
        modelsMap.put("activehybrid 5", "ACTIVE5");
        modelsMap.put("6 series (13)", "6_SERIES");
        modelsMap.put("633csi", "633CSI");
        modelsMap.put("635csi", "635CSI");
        modelsMap.put("640i", "640I");
        modelsMap.put("640i gran coupe", "640IGC");
        modelsMap.put("640i gran coupe xdrive", "BMW640GCXD");
        modelsMap.put("640i xdrive", "BMW640IXD");
        modelsMap.put("645ci", "645CI");
        modelsMap.put("650i", "650I");
        modelsMap.put("650i gran coupe", "650IGC");
        modelsMap.put("650i gran coupe xdrive", "650IGCXD");
        modelsMap.put("650i xdrive", "650IXD");
        modelsMap.put("alpina b6 xdrive gran coupe", "BMWB6XDGC");
        modelsMap.put("l6", "L6");
        modelsMap.put("7 series (21)", "7_SERIES");
        modelsMap.put("733i", "733I");
        modelsMap.put("735i", "735I");
        modelsMap.put("735il", "735IL");
        modelsMap.put("740ld xdrive", "BMW740LDXD");
        modelsMap.put("740li", "740LI");
        modelsMap.put("740li xdrive", "740LIXD");
        modelsMap.put("740i", "740I");
        modelsMap.put("740il", "740IL");
        modelsMap.put("745li", "745LI");
        modelsMap.put("745i", "745I");
        modelsMap.put("750li", "750LI");
        modelsMap.put("750li xdrive", "750LIXD");
        modelsMap.put("750i", "750I");
        modelsMap.put("750i xdrive", "750IXD");
        modelsMap.put("750il", "750IL");
        modelsMap.put("760li", "760LI");
        modelsMap.put("760i", "760I");
        modelsMap.put("alpina b7", "ALPINAB7");
        modelsMap.put("alpina b7 xdrive", "ALPINAB7XD");
        modelsMap.put("activehybrid 7", "ACTIVE7");
        modelsMap.put("l7", "L7");
        modelsMap.put("8 series (4)", "8_SERIES");
        modelsMap.put("840ci", "840CI");
        modelsMap.put("850csi", "850CSI");
        modelsMap.put("850ci", "850CI");
        modelsMap.put("850i", "850I");
        modelsMap.put("activehybrid x6", "ACTIVEX6");
        modelsMap.put("i3", "BMWI3");
        modelsMap.put("i8", "BMWI8");
        modelsMap.put("m coupe", "BMWMCOUPE");
        modelsMap.put("m roadster", "BMWROAD");
        modelsMap.put("m3", "M3");
        modelsMap.put("m4", "BMWM4");
        modelsMap.put("m5", "M5");
        modelsMap.put("m6", "M6");
        modelsMap.put("m6 gran coupe", "BMWM6GC");
        modelsMap.put("x1", "X1");
        modelsMap.put("x3", "X3");
        modelsMap.put("x4", "BMWX4");
        modelsMap.put("x5", "X5");
        modelsMap.put("x5 m", "X5M");
        modelsMap.put("x6", "X6");
        modelsMap.put("x6 m", "X6M");
        modelsMap.put("z3", "Z3");
        modelsMap.put("z4", "Z4");
        modelsMap.put("z8", "Z8");
        modelsMap.put("other bmw models", "BMWOTH");
        modelsMap.put("century", "CENT");
        modelsMap.put("electra", "ELEC");
        modelsMap.put("enclave", "ENCLAVE");
        modelsMap.put("encore", "BUIENC");
        modelsMap.put("lacrosse", "LACROSSE");
        modelsMap.put("le sabre", "LESA");
        modelsMap.put("lucerne", "LUCERNE");
        modelsMap.put("park avenue", "PARK");
        modelsMap.put("rainier", "RAINIER");
        modelsMap.put("reatta", "REATTA");
        modelsMap.put("regal", "REG");
        modelsMap.put("rendezvous", "RENDEZVOUS");
        modelsMap.put("riviera", "RIV");
        modelsMap.put("roadmaster", "BUICKROAD");
        modelsMap.put("skyhawk", "SKYH");
        modelsMap.put("skylark", "SKYL");
        modelsMap.put("somerset", "SOMER");
        modelsMap.put("terraza", "TERRAZA");
        modelsMap.put("verano", "BUVERANO");
        modelsMap.put("other buick models", "BUOTH");
        modelsMap.put("allante", "ALLANT");
        modelsMap.put("ats", "ATS");
        modelsMap.put("brougham", "BROUGH");
        modelsMap.put("catera", "CATERA");
        modelsMap.put("cimarron", "CIMA");
        modelsMap.put("ct6", "CADCT6");
        modelsMap.put("cts", "CTS");
        modelsMap.put("de ville", "DEV");
        modelsMap.put("dts", "DTS");
        modelsMap.put("eldorado", "ELDO");
        modelsMap.put("elr", "CADELR");
        modelsMap.put("escalade", "ESCALA");
        modelsMap.put("escalade esv", "ESCALAESV");
        modelsMap.put("escalade ext", "EXT");
        modelsMap.put("fleetwood", "FLEE");
        modelsMap.put("seville", "SEV");
        modelsMap.put("srx", "SRX");
        modelsMap.put("sts", "STS");
        modelsMap.put("xlr", "XLR");
        modelsMap.put("xts", "XTS");
        modelsMap.put("other cadillac models", "CADOTH");
        modelsMap.put("astro", "ASTRO");
        modelsMap.put("avalanche", "AVALNCH");
        modelsMap.put("aveo", "AVEO");
        modelsMap.put("aveo5", "AVEO5");
        modelsMap.put("beretta", "BERETT");
        modelsMap.put("blazer", "BLAZER");
        modelsMap.put("camaro", "CAM");
        modelsMap.put("caprice", "CAP");
        modelsMap.put("captiva sport", "CHECAPS");
        modelsMap.put("cavalier", "CAV");
        modelsMap.put("celebrity", "CELE");
        modelsMap.put("chevette", "CHEVETTE");
        modelsMap.put("citation", "CITATION");
        modelsMap.put("city express", "CHECITYEXP");
        modelsMap.put("cobalt", "COBALT");
        modelsMap.put("colorado", "COLORADO");
        modelsMap.put("corsica", "CORSI");
        modelsMap.put("corvette", "CORV");
        modelsMap.put("cruze", "CRUZE");
        modelsMap.put("el camino", "ELCAM");
        modelsMap.put("equinox", "EQUINOX");
        modelsMap.put("express 1500", "CHEXP1500");
        modelsMap.put("express 2500", "CHEXP2500");
        modelsMap.put("express 3500", "CHEXP3500");
        modelsMap.put("express 4500", "CHEXP4500");
        modelsMap.put("g10", "CHEG10");
        modelsMap.put("g20", "CHEG20");
        modelsMap.put("g30", "CHEG30");
        modelsMap.put("hhr", "HHR");
        modelsMap.put("impala", "CHEVIMP");
        modelsMap.put("kodiak c4500", "KODC4500");
        modelsMap.put("lumina", "LUMINA");
        modelsMap.put("lumina apv", "LAPV");
        modelsMap.put("luv", "LUV");
        modelsMap.put("malibu", "MALI");
        modelsMap.put("metro", "CHVMETR");
        modelsMap.put("monte carlo", "CHEVMONT");
        modelsMap.put("nova", "NOVA");
        modelsMap.put("prizm", "CHEVPRIZM");
        modelsMap.put("s10 blazer", "CHVST");
        modelsMap.put("s10 pickup", "S10PICKUP");
        modelsMap.put("silverado and other c/k1500", "CHEV150");
        modelsMap.put("silverado and other c/k2500", "CHEVC25");
        modelsMap.put("silverado and other c/k3500", "CH3500PU");
        modelsMap.put("sonic", "SONIC");
        modelsMap.put("spark", "SPARK");
        modelsMap.put("spectrum", "CHEVSPEC");
        modelsMap.put("sprint", "CHSPRINT");
        modelsMap.put("ss", "CHEVSS");
        modelsMap.put("ssr", "SSR");
        modelsMap.put("suburban", "CHEVSUB");
        modelsMap.put("tahoe", "TAHOE");
        modelsMap.put("tracker", "TRACKE");
        modelsMap.put("trailblazer", "TRAILBLZ");
        modelsMap.put("trailblazer ext", "TRAILBZEXT");
        modelsMap.put("traverse", "TRAVERSE");
        modelsMap.put("trax", "CHETRAX");
        modelsMap.put("uplander", "UPLANDER");
        modelsMap.put("venture", "VENTUR");
        modelsMap.put("volt", "VOLT");
        modelsMap.put("other chevrolet models", "CHEOTH");
        modelsMap.put("200", "CHRYS200");
        modelsMap.put("300", "300");
        modelsMap.put("300m", "CHRY300");
        modelsMap.put("aspen", "ASPEN");
        modelsMap.put("cirrus", "CIRRUS");
        modelsMap.put("concorde", "CONC");
        modelsMap.put("conquest", "CHRYCONQ");
        modelsMap.put("cordoba", "CORDOBA");
        modelsMap.put("crossfire", "CROSSFIRE");
        modelsMap.put("e class", "ECLASS");
        modelsMap.put("fifth avenue", "FIFTH");
        modelsMap.put("grand voyager", "CHRYGRANDV");
        modelsMap.put("imperial", "IMPE");
        modelsMap.put("intrepid", "INTREPID");
        modelsMap.put("laser", "CHRYLAS");
        modelsMap.put("lebaron", "LEBA");
        modelsMap.put("lebaron gts", "CHRYLEBGTS");
        modelsMap.put("lhs", "LHS");
        modelsMap.put("new yorker", "NY");
        modelsMap.put("newport", "NEWPORT");
        modelsMap.put("pacifica", "PACIFICA");
        modelsMap.put("prowler", "CHPROWLE");
        modelsMap.put("pt cruiser", "PTCRUIS");
        modelsMap.put("sebring", "CHRYSEB");
        modelsMap.put("tc by maserati", "CHRYTC");
        modelsMap.put("town & country", "TANDC");
        modelsMap.put("voyager", "VOYAGER");
        modelsMap.put("other chrysler models", "CHOTH");
        modelsMap.put("lanos", "LANOS");
        modelsMap.put("leganza", "LEGANZA");
        modelsMap.put("nubira", "NUBIRA");
        modelsMap.put("other daewoo models", "DAEOTH");
        modelsMap.put("200sx", "DAT200SX");
        modelsMap.put("210", "DAT210");
        modelsMap.put("280zx", "280Z");
        modelsMap.put("300zx", "300ZX");
        modelsMap.put("310", "310");
        modelsMap.put("510", "510");
        modelsMap.put("720", "720");
        modelsMap.put("810", "810");
        modelsMap.put("maxima", "DATMAX");
        modelsMap.put("pickup", "DATPU");
        modelsMap.put("pulsar", "PUL");
        modelsMap.put("sentra", "DATSENT");
        modelsMap.put("stanza", "STAN");
        modelsMap.put("other datsun models", "DATOTH");
        modelsMap.put("dmc-12", "DMC12");
        modelsMap.put("400", "400");
        modelsMap.put("600", "DOD600");
        modelsMap.put("aries", "ARI");
        modelsMap.put("avenger", "AVENGR");
        modelsMap.put("b150", "B150");
        modelsMap.put("b1500", "B1500");
        modelsMap.put("b250", "B250");
        modelsMap.put("b2500", "B2500");
        modelsMap.put("b350", "B350");
        modelsMap.put("b3500", "B3500");
        modelsMap.put("caliber", "CALIBER");
        modelsMap.put("caravan", "DODCARA");
        modelsMap.put("challenger", "CHALLENGER");
        modelsMap.put("charger", "DODCHAR");
        modelsMap.put("colt", "DODCOLT");
        modelsMap.put("conquest", "DODCONQ");
        modelsMap.put("d/w truck", "DODDW");
        modelsMap.put("dakota", "DAKOTA");
        modelsMap.put("dart", "DODDART");
        modelsMap.put("daytona", "DAY");
        modelsMap.put("diplomat", "DIPLOMA");
        modelsMap.put("durango", "DURANG");
        modelsMap.put("dynasty", "DODDYNA");
        modelsMap.put("grand caravan", "GRANDCARAV");
        modelsMap.put("intrepid", "INTRE");
        modelsMap.put("journey", "JOURNEY");
        modelsMap.put("lancer", "LANCERDODG");
        modelsMap.put("magnum", "MAGNUM");
        modelsMap.put("mini ram van", "RAMVANV8");
        modelsMap.put("mirada", "MIRADA");
        modelsMap.put("monaco", "MONACO");
        modelsMap.put("neon", "DODNEON");
        modelsMap.put("nitro", "NITRO");
        modelsMap.put("omni", "OMNI");
        modelsMap.put("raider", "RAIDER");
        modelsMap.put("ram 1500 truck", "RAM1504WD");
        modelsMap.put("ram 2500 truck", "RAM25002WD");
        modelsMap.put("ram 3500 truck", "RAM3502WD");
        modelsMap.put("ram 4500 truck", "RAM4500");
        modelsMap.put("ram 50 truck", "DODD50");
        modelsMap.put("ram 5500 truck", "RAM5500");
        modelsMap.put("ram srt-10", "RAMSRT10");
        modelsMap.put("ramcharger", "RAMCGR");
        modelsMap.put("rampage", "RAMPAGE");
        modelsMap.put("shadow", "DODSHAD");
        modelsMap.put("spirit", "DODSPIR");
        modelsMap.put("sprinter", "SPRINTER");
        modelsMap.put("srt-4", "SRT4");
        modelsMap.put("st. regis", "STREGIS");
        modelsMap.put("stealth", "STEAL");
        modelsMap.put("stratus", "STRATU");
        modelsMap.put("viper", "VIPER");
        modelsMap.put("other dodge models", "DOOTH");
        modelsMap.put("medallion", "EAGLEMED");
        modelsMap.put("premier", "EAGLEPREM");
        modelsMap.put("summit", "SUMMIT");
        modelsMap.put("talon", "TALON");
        modelsMap.put("vision", "VISION");
        modelsMap.put("other eagle models", "EAGOTH");
        modelsMap.put("308", "308");
        modelsMap.put("328", "328");
        modelsMap.put("348", "348");
        modelsMap.put("360", "360");
        modelsMap.put("456 gt", "456GT");
        modelsMap.put("456m gt", "456MGT");
        modelsMap.put("458 italia", "458ITALIA");
        modelsMap.put("512m", "512M");
        modelsMap.put("512tr", "512TR");
        modelsMap.put("550 maranello", "550M");
        modelsMap.put("575m maranello", "575M");
        modelsMap.put("599 gtb fiorano", "599GTB");
        modelsMap.put("599 gto", "599GTO");
        modelsMap.put("612 scaglietti", "612SCAGLIE");
        modelsMap.put("california", "FERCALIF");
        modelsMap.put("enzo", "ENZO");
        modelsMap.put("f12 berlinetta", "FERF12BERL");
        modelsMap.put("f355", "F355");
        modelsMap.put("f40", "F40");
        modelsMap.put("f430", "F430");
        modelsMap.put("f50", "F50");
        modelsMap.put("ff", "FERFF");
        modelsMap.put("mondial", "MOND");
        modelsMap.put("testarossa", "TEST");
        modelsMap.put("other ferrari models", "FEROTH");
        modelsMap.put("2000 spider", "2000");
        modelsMap.put("500", "FIAT500");
        modelsMap.put("500l", "FIAT500L");
        modelsMap.put("500x", "FIAT500X");
        modelsMap.put("bertone x1/9", "BERTON");
        modelsMap.put("brava", "BRAVA");
        modelsMap.put("pininfarina spider", "PININ");
        modelsMap.put("strada", "STRADA");
        modelsMap.put("x1/9", "FIATX19");
        modelsMap.put("other fiat models", "FIAOTH");
        modelsMap.put("karma", "KARMA");
        modelsMap.put("aerostar", "AERO");
        modelsMap.put("aspire", "ASPIRE");
        modelsMap.put("bronco", "BRON");
        modelsMap.put("bronco ii", "B2");
        modelsMap.put("c-max", "FOCMAX");
        modelsMap.put("contour", "CONTOUR");
        modelsMap.put("courier", "COURIER");
        modelsMap.put("crown victoria", "CROWNVIC");
        modelsMap.put("e-100", "E100ECON");
        modelsMap.put("e-150 and econoline 150", "E150ECON");
        modelsMap.put("e-250 and econoline 250", "E250ECON");
        modelsMap.put("e-350 and econoline 350", "E350ECON");
        modelsMap.put("edge", "EDGE");
        modelsMap.put("escape", "ESCAPE");
        modelsMap.put("escort", "ESCO");
        modelsMap.put("excursion", "EXCURSION");
        modelsMap.put("exp", "EXP");
        modelsMap.put("expedition", "EXPEDI");
        modelsMap.put("expedition el", "EXPEDIEL");
        modelsMap.put("explorer", "EXPLOR");
        modelsMap.put("explorer sport trac", "SPORTTRAC");
        modelsMap.put("f100", "F100");
        modelsMap.put("f150", "F150PICKUP");
        modelsMap.put("f250", "F250");
        modelsMap.put("f350", "F350");
        modelsMap.put("f450", "F450");
        modelsMap.put("fairmont", "FAIRM");
        modelsMap.put("festiva", "FESTIV");
        modelsMap.put("fiesta", "FIESTA");
        modelsMap.put("five hundred", "FIVEHUNDRE");
        modelsMap.put("flex", "FLEX");
        modelsMap.put("focus", "FOCUS");
        modelsMap.put("freestar", "FREESTAR");
        modelsMap.put("freestyle", "FREESTYLE");
        modelsMap.put("fusion", "FUSION");
        modelsMap.put("granada", "GRANADA");
        modelsMap.put("gt", "GT");
        modelsMap.put("ltd", "LTD");
        modelsMap.put("mustang", "MUST");
        modelsMap.put("probe", "PROBE");
        modelsMap.put("ranger", "RANGER");
        modelsMap.put("taurus", "TAURUS");
        modelsMap.put("taurus x", "TAURUSX");
        modelsMap.put("tempo", "TEMPO");
        modelsMap.put("thunderbird", "TBIRD");
        modelsMap.put("transit 150", "FORDTRN150");
        modelsMap.put("transit 250", "FORDTRN250");
        modelsMap.put("transit 350", "FORDTRN350");
        modelsMap.put("transit connect", "TRANSCONN");
        modelsMap.put("windstar", "WINDST");
        modelsMap.put("zx2 escort", "FORDZX2");
        modelsMap.put("other ford models", "FOOTH");
        modelsMap.put("sprinter", "FRESPRINT");
        modelsMap.put("metro", "GEOMETRO");
        modelsMap.put("prizm", "GEOPRIZM");
        modelsMap.put("spectrum", "SPECT");
        modelsMap.put("storm", "STORM");
        modelsMap.put("tracker", "GEOTRACK");
        modelsMap.put("other geo models", "GEOOTH");
        modelsMap.put("acadia", "ACADIA");
        modelsMap.put("caballero", "CABALLERO");
        modelsMap.put("canyon", "CANYON");
        modelsMap.put("envoy", "ENVOY");
        modelsMap.put("envoy xl", "ENVOYXL");
        modelsMap.put("envoy xuv", "ENVOYXUV");
        modelsMap.put("g1500", "G1500");
        modelsMap.put("g2500", "G2500");
        modelsMap.put("g3500", "G3500");
        modelsMap.put("jimmy", "JIM");
        modelsMap.put("s15 jimmy", "GMCS15");
        modelsMap.put("s15 pickup", "S15");
        modelsMap.put("safari", "SAFARIGMC");
        modelsMap.put("savana 1500", "GMCSAVANA");
        modelsMap.put("savana 2500", "GMCSAV2500");
        modelsMap.put("savana 3500", "GMCSAV3500");
        modelsMap.put("savana 4500", "GMCSAV4500");
        modelsMap.put("sierra c/k1500", "15SIPU4WD");
        modelsMap.put("sierra c/k2500", "GMCC25PU");
        modelsMap.put("sierra c/k3500", "GMC3500PU");
        modelsMap.put("sonoma", "SONOMA");
        modelsMap.put("suburban", "SUB");
        modelsMap.put("syclone", "GMCSYCLON");
        modelsMap.put("terrain", "TERRAIN");
        modelsMap.put("topkick c4500", "TOPC4500");
        modelsMap.put("typhoon", "TYPH");
        modelsMap.put("yukon", "YUKON");
        modelsMap.put("yukon xl", "YUKONXL");
        modelsMap.put("other gmc models", "GMCOTH");
        modelsMap.put("accord", "ACCORD");
        modelsMap.put("civic", "CIVIC");
        modelsMap.put("cr-v", "CRV");
        modelsMap.put("cr-z", "CRZ");
        modelsMap.put("crx", "CRX");
        modelsMap.put("crosstour models (2)", "CROSSTOUR_MODELS");
        modelsMap.put("accord crosstour", "CROSSTOUR");
        modelsMap.put("crosstour", "HONCROSS");
        modelsMap.put("del sol", "HONDELSOL");
        modelsMap.put("element", "ELEMENT");
        modelsMap.put("fit", "FIT");
        modelsMap.put("hr-v", "HONHRV");
        modelsMap.put("insight", "INSIGHT");
        modelsMap.put("odyssey", "ODYSSEY");
        modelsMap.put("passport", "PASSPO");
        modelsMap.put("pilot", "PILOT");
        modelsMap.put("prelude", "PRE");
        modelsMap.put("ridgeline", "RIDGELINE");
        modelsMap.put("s2000", "S2000");
        modelsMap.put("other honda models", "HONOTH");
        modelsMap.put("h1", "HUMMER");
        modelsMap.put("h2", "H2");
        modelsMap.put("h3", "H3");
        modelsMap.put("h3t", "H3T");
        modelsMap.put("other hummer models", "AMGOTH");
        modelsMap.put("accent", "ACCENT");
        modelsMap.put("azera", "AZERA");
        modelsMap.put("elantra", "ELANTR");
        modelsMap.put("elantra coupe", "HYUELANCPE");
        modelsMap.put("elantra touring", "ELANTOUR");
        modelsMap.put("entourage", "ENTOURAGE");
        modelsMap.put("equus", "EQUUS");
        modelsMap.put("excel", "HYUEXCEL");
        modelsMap.put("genesis", "GENESIS");
        modelsMap.put("genesis coupe", "GENESISCPE");
        modelsMap.put("santa fe", "SANTAFE");
        modelsMap.put("scoupe", "SCOUPE");
        modelsMap.put("sonata", "SONATA");
        modelsMap.put("tiburon", "TIBURO");
        modelsMap.put("tucson", "TUCSON");
        modelsMap.put("veloster", "VELOSTER");
        modelsMap.put("veracruz", "VERACRUZ");
        modelsMap.put("xg300", "XG300");
        modelsMap.put("xg350", "XG350");
        modelsMap.put("other hyundai models", "HYUOTH");
        modelsMap.put("ex models (2)", "EX_MODELS");
        modelsMap.put("ex35", "EX35");
        modelsMap.put("ex37", "EX37");
        modelsMap.put("fx models (4)", "FX_MODELS");
        modelsMap.put("fx35", "FX35");
        modelsMap.put("fx37", "FX37");
        modelsMap.put("fx45", "FX45");
        modelsMap.put("fx50", "FX50");
        modelsMap.put("g models (4)", "G_MODELS");
        modelsMap.put("g20", "G20");
        modelsMap.put("g25", "G25");
        modelsMap.put("g35", "G35");
        modelsMap.put("g37", "G37");
        modelsMap.put("i30", "I30");
        modelsMap.put("i35", "I35");
        modelsMap.put("j30", "J30");
        modelsMap.put("jx35", "JX35");
        modelsMap.put("m models (6)", "M_MODELS");
        modelsMap.put("m30", "M30");
        modelsMap.put("m35", "M35");
        modelsMap.put("m35h", "M35HYBRID");
        modelsMap.put("m37", "M37");
        modelsMap.put("m45", "M45");
        modelsMap.put("m56", "M56");
        modelsMap.put("q40", "INFINQ40");
        modelsMap.put("q45", "Q45");
        modelsMap.put("q50", "INFINQ50");
        modelsMap.put("q60", "INFINQ60");
        modelsMap.put("q70", "INFINQ70");
        modelsMap.put("qx4", "QX4");
        modelsMap.put("qx50", "INFINQX50");
        modelsMap.put("qx56", "QX56");
        modelsMap.put("qx60", "INFINQX60");
        modelsMap.put("qx70", "INFINQX70");
        modelsMap.put("qx80", "INFINQX80");
        modelsMap.put("other infiniti models", "INFOTH");
        modelsMap.put("amigo", "AMIGO");
        modelsMap.put("ascender", "ASCENDER");
        modelsMap.put("axiom", "AXIOM");
        modelsMap.put("hombre", "HOMBRE");
        modelsMap.put("i-280", "I280");
        modelsMap.put("i-290", "I290");
        modelsMap.put("i-350", "I350");
        modelsMap.put("i-370", "I370");
        modelsMap.put("i-mark", "ISUMARK");
        modelsMap.put("impulse", "ISUIMP");
        modelsMap.put("oasis", "OASIS");
        modelsMap.put("pickup", "ISUPU");
        modelsMap.put("rodeo", "RODEO");
        modelsMap.put("stylus", "STYLUS");
        modelsMap.put("trooper", "TROOP");
        modelsMap.put("trooper ii", "TRP2");
        modelsMap.put("vehicross", "VEHICROSS");
        modelsMap.put("other isuzu models", "ISUOTH");
        modelsMap.put("f-type", "JAGFTYPE");
        modelsMap.put("s-type", "STYPE");
        modelsMap.put("x-type", "XTYPE");
        modelsMap.put("xf", "XF");
        modelsMap.put("xj series (10)", "XJ_SERIES");
        modelsMap.put("xj", "XJ");
        modelsMap.put("xj sport", "XJSPORT");
        modelsMap.put("xj vanden plas", "VANDEN");
        modelsMap.put("xj12", "JAGXJ12");
        modelsMap.put("xj6", "JAGXJ6");
        modelsMap.put("xj8", "XJ8");
        modelsMap.put("xj8 l", "XJ8L");
        modelsMap.put("xjr", "JAGXJR");
        modelsMap.put("xjr-s", "JAGXJRS");
        modelsMap.put("xjs", "JAGXJS");
        modelsMap.put("xk series (3)", "XK_SERIES");
        modelsMap.put("xk", "XK");
        modelsMap.put("xk8", "JAGXK8");
        modelsMap.put("xkr", "XKR");
        modelsMap.put("other jaguar models", "JAGOTH");
        modelsMap.put("cherokee", "CHER");
        modelsMap.put("cj", "JEEPCJ");
        modelsMap.put("comanche", "COMANC");
        modelsMap.put("commander", "COMMANDER");
        modelsMap.put("compass", "COMPASS");
        modelsMap.put("grand cherokee", "JEEPGRAND");
        modelsMap.put("grand wagoneer", "GRWAG");
        modelsMap.put("liberty", "LIBERTY");
        modelsMap.put("patriot", "PATRIOT");
        modelsMap.put("pickup", "JEEPPU");
        modelsMap.put("renegade", "JEEPRENEG");
        modelsMap.put("scrambler", "SCRAMBLE");
        modelsMap.put("wagoneer", "WAGONE");
        modelsMap.put("wrangler", "WRANGLER");
        modelsMap.put("other jeep models", "JEOTH");
        modelsMap.put("amanti", "AMANTI");
        modelsMap.put("borrego", "BORREGO");
        modelsMap.put("cadenza", "KIACADENZA");
        modelsMap.put("forte", "FORTE");
        modelsMap.put("forte koup", "FORTEKOUP");
        modelsMap.put("k900", "KIAK900");
        modelsMap.put("optima", "OPTIMA");
        modelsMap.put("rio", "RIO");
        modelsMap.put("rio5", "RIO5");
        modelsMap.put("rondo", "RONDO");
        modelsMap.put("sedona", "SEDONA");
        modelsMap.put("sephia", "SEPHIA");
        modelsMap.put("sorento", "SORENTO");
        modelsMap.put("soul", "SOUL");
        modelsMap.put("spectra", "SPECTRA");
        modelsMap.put("spectra5", "SPECTRA5");
        modelsMap.put("sportage", "SPORTA");
        modelsMap.put("other kia models", "KIAOTH");
        modelsMap.put("aventador", "AVENT");
        modelsMap.put("countach", "COUNT");
        modelsMap.put("diablo", "DIABLO");
        modelsMap.put("gallardo", "GALLARDO");
        modelsMap.put("huracan", "LAMHURACAN");
        modelsMap.put("jalpa", "JALPA");
        modelsMap.put("lm002", "LM002");
        modelsMap.put("murcielago", "MURCIELAGO");
        modelsMap.put("other lamborghini models", "LAMOTH");
        modelsMap.put("defender", "DEFEND");
        modelsMap.put("discovery", "DISCOV");
        modelsMap.put("discovery sport", "ROVDISCSPT");
        modelsMap.put("freelander", "FRELNDR");
        modelsMap.put("lr2", "LR2");
        modelsMap.put("lr3", "LR3");
        modelsMap.put("lr4", "LR4");
        modelsMap.put("range rover", "RANGE");
        modelsMap.put("range rover evoque", "EVOQUE");
        modelsMap.put("range rover sport", "RANGESPORT");
        modelsMap.put("other land rover models", "ROVOTH");
        modelsMap.put("ct 200h", "CT200H");
        modelsMap.put("es models (5)", "ES_MODELS");
        modelsMap.put("es 250", "ES250");
        modelsMap.put("es 300", "ES300");
        modelsMap.put("es 300h", "ES300H");
        modelsMap.put("es 330", "ES330");
        modelsMap.put("es 350", "ES350");
        modelsMap.put("gs models (6)", "GS_MODELS");
        modelsMap.put("gs 300", "GS300");
        modelsMap.put("gs 350", "GS350");
        modelsMap.put("gs 400", "GS400");
        modelsMap.put("gs 430", "GS430");
        modelsMap.put("gs 450h", "GS450H");
        modelsMap.put("gs 460", "GS460");
        modelsMap.put("gx models (2)", "GX_MODELS");
        modelsMap.put("gx 460", "GX460");
        modelsMap.put("gx 470", "GX470");
        modelsMap.put("hs 250h", "HS250H");
        modelsMap.put("is models (7)", "IS_MODELS");
        modelsMap.put("is 200t", "LEXIS200T");
        modelsMap.put("is 250", "IS250");
        modelsMap.put("is 250c", "IS250C");
        modelsMap.put("is 300", "IS300");
        modelsMap.put("is 350", "IS350");
        modelsMap.put("is 350c", "IS350C");
        modelsMap.put("is f", "ISF");
        modelsMap.put("lfa", "LEXLFA");
        modelsMap.put("ls models (4)", "LS_MODELS");
        modelsMap.put("ls 400", "LS400");
        modelsMap.put("ls 430", "LS430");
        modelsMap.put("ls 460", "LS460");
        modelsMap.put("ls 600h", "LS600H");
        modelsMap.put("lx models (3)", "LX_MODELS");
        modelsMap.put("lx 450", "LX450");
        modelsMap.put("lx 470", "LX470");
        modelsMap.put("lx 570", "LX570");
        modelsMap.put("nx models (2)", "NX_MODELS");
        modelsMap.put("nx 200t", "LEXNX200T");
        modelsMap.put("nx 300h", "LEXNX300H");
        modelsMap.put("rc models (2)", "RC_MODELS");
        modelsMap.put("rc 350", "LEXRC350");
        modelsMap.put("rc f", "LEXRCF");
        modelsMap.put("rx models (5)", "RX_MODELS");
        modelsMap.put("rx 300", "RX300");
        modelsMap.put("rx 330", "RX330");
        modelsMap.put("rx 350", "RX350");
        modelsMap.put("rx 400h", "RX400H");
        modelsMap.put("rx 450h", "RX450H");
        modelsMap.put("sc models (3)", "SC_MODELS");
        modelsMap.put("sc 300", "SC300");
        modelsMap.put("sc 400", "SC400");
        modelsMap.put("sc 430", "SC430");
        modelsMap.put("other lexus models", "LEXOTH");
        modelsMap.put("aviator", "AVIATOR");
        modelsMap.put("blackwood", "BLKWOOD");
        modelsMap.put("continental", "CONT");
        modelsMap.put("ls", "LSLINCOLN");
        modelsMap.put("mark lt", "MARKLT");
        modelsMap.put("mark vi", "MARK6");
        modelsMap.put("mark vii", "MARK7");
        modelsMap.put("mark viii", "MARK8");
        modelsMap.put("mkc", "LINCMKC");
        modelsMap.put("mks", "MKS");
        modelsMap.put("mkt", "MKT");
        modelsMap.put("mkx", "MKX");
        modelsMap.put("mkz", "MKZ");
        modelsMap.put("navigator", "NAVIGA");
        modelsMap.put("navigator l", "NAVIGAL");
        modelsMap.put("town car", "LINCTC");
        modelsMap.put("zephyr", "ZEPHYR");
        modelsMap.put("other lincoln models", "LINOTH");
        modelsMap.put("elan", "ELAN");
        modelsMap.put("elise", "LOTELISE");
        modelsMap.put("esprit", "ESPRIT");
        modelsMap.put("evora", "EVORA");
        modelsMap.put("exige", "EXIGE");
        modelsMap.put("other lotus models", "LOTOTH");
        modelsMap.put("430", "430");
        modelsMap.put("biturbo", "BITRBO");
        modelsMap.put("coupe", "COUPEMAS");
        modelsMap.put("ghibli", "GHIB");
        modelsMap.put("gransport", "GRANSPORT");
        modelsMap.put("granturismo", "GRANTURISM");
        modelsMap.put("quattroporte", "QP");
        modelsMap.put("spyder", "SPYDER");
        modelsMap.put("other maserati models", "MASOTH");



        modelsMap.put("57", "57MAYBACH");
        modelsMap.put("62", "62MAYBACH");
        modelsMap.put("323", "MAZDA323");
        modelsMap.put("626", "MAZDA626");
        modelsMap.put("929", "929");
        modelsMap.put("b-series pickup", "B-SERIES");
        modelsMap.put("cx-3", "MAZCX3");
        modelsMap.put("cx-5", "CX-5");
        modelsMap.put("cx-7", "CX-7");
        modelsMap.put("cx-9", "CX-9");
        modelsMap.put("glc", "GLC");
        modelsMap.put("mazda2", "MAZDA2");
        modelsMap.put("mazda3", "MAZDA3");
        modelsMap.put("mazda5", "MAZDA5");
        modelsMap.put("mazda6", "MAZDA6");
        modelsMap.put("mazdaspeed3", "MAZDASPD3");
        modelsMap.put("mazdaspeed6", "MAZDASPD6");
        modelsMap.put("millenia", "MILL");
        modelsMap.put("mpv", "MPV");
        modelsMap.put("mx-5 miata", "MIATA");
        modelsMap.put("mx3", "MX3");
        modelsMap.put("mx6", "MX6");
        modelsMap.put("navajo", "NAVAJO");
        modelsMap.put("protege", "PROTE");
        modelsMap.put("protege5", "PROTE5");
        modelsMap.put("rx-7", "RX7");
        modelsMap.put("rx-8", "RX8");
        modelsMap.put("tribute", "TRIBUTE");
        modelsMap.put("other mazda models", "MAZOTH");
        modelsMap.put("570s", "MCL570S");
        modelsMap.put("650s", "MCL650S");
        modelsMap.put("mp4-12c", "MP4");
        modelsMap.put("p1", "MCLP1");
        modelsMap.put("190d", "190D");
        modelsMap.put("190e", "190E");
        modelsMap.put("240d", "240D");
        modelsMap.put("260e", "260E");
        modelsMap.put("280ce", "280CE");
        modelsMap.put("280e", "280E");
        modelsMap.put("300cd", "300CD");
        modelsMap.put("300ce", "300CE");
        modelsMap.put("300d", "300D");
        modelsMap.put("300e", "300E");
        modelsMap.put("300sd", "300SD");
        modelsMap.put("300sdl", "300SDL");
        modelsMap.put("300se", "300SE");
        modelsMap.put("300sel", "300SEL");
        modelsMap.put("300sl", "300SL");
        modelsMap.put("300td", "300TD");
        modelsMap.put("300te", "300TE");
        modelsMap.put("350sd", "350SD");
        modelsMap.put("350sdl", "350SDL");
        modelsMap.put("380se", "380SE");
        modelsMap.put("380sec", "380SEC");
        modelsMap.put("380sel", "380SEL");
        modelsMap.put("380sl", "380SL");
        modelsMap.put("380slc", "380SLC");
        modelsMap.put("400e", "400E");
        modelsMap.put("400se", "400SE");
        modelsMap.put("400sel", "400SEL");
        modelsMap.put("420sel", "420SEL");
        modelsMap.put("500e", "500E");
        modelsMap.put("500sec", "500SEC");
        modelsMap.put("500sel", "500SEL");
        modelsMap.put("500sl", "500SL");
        modelsMap.put("560sec", "560SEC");
        modelsMap.put("560sel", "560SEL");
        modelsMap.put("560sl", "560SL");
        modelsMap.put("600sec", "600SEC");
        modelsMap.put("600sel", "600SEL");
        modelsMap.put("600sl", "600SL");
        modelsMap.put("amg gt", "MBAMGGT");
        modelsMap.put("b-class electric drive", "MBBCLASSED");
        modelsMap.put("c-class (15)", "C_CLASS");
        modelsMap.put("c220", "C220");
        modelsMap.put("c230", "C230");
        modelsMap.put("c240", "C240");
        modelsMap.put("c250", "C250");
        modelsMap.put("c280", "C280");
        modelsMap.put("c300", "C300");
        modelsMap.put("c32 amg", "C32AMG");
        modelsMap.put("c320", "C320");
        modelsMap.put("c350", "C350");
        modelsMap.put("c36 amg", "C36AMG");
        modelsMap.put("c400", "MBC400");
        modelsMap.put("c43 amg", "C43AMG");
        modelsMap.put("c450", "MBC450");
        modelsMap.put("c55 amg", "C55AMG");
        modelsMap.put("c63 amg", "C63AMG");
        modelsMap.put("cl-class (6)", "CL_CLASS");
        modelsMap.put("cl500", "CL500");
        modelsMap.put("cl55 amg", "CL55AMG");
        modelsMap.put("cl550", "CL550");
        modelsMap.put("cl600", "CL600");
        modelsMap.put("cl63 amg", "CL63AMG");
        modelsMap.put("cl65 amg", "CL65AMG");
        modelsMap.put("cla-class (2)", "CLA_CLASS");
        modelsMap.put("cla250", "MBCLA250");
        modelsMap.put("cla45 amg", "MBCLA45AMG");
        modelsMap.put("clk-class (7)", "CLK_CLASS");
        modelsMap.put("clk320", "CLK320");
        modelsMap.put("clk350", "CLK350");
        modelsMap.put("clk430", "CLK430");
        modelsMap.put("clk500", "CLK500");
        modelsMap.put("clk55 amg", "CLK55AMG");
        modelsMap.put("clk550", "CLK550");
        modelsMap.put("clk63 amg", "CLK63AMG");
        modelsMap.put("cls-class (5)", "CLS_CLASS");
        modelsMap.put("cls400", "MBCLS400");
        modelsMap.put("cls500", "CLS500");
        modelsMap.put("cls55 amg", "CLS55AMG");
        modelsMap.put("cls550", "CLS550");
        modelsMap.put("cls63 amg", "CLS63AMG");
        modelsMap.put("e-class (11)", "E_CLASS");
        modelsMap.put("e250", "MBE250BLUE");
        modelsMap.put("e300", "E300");
        modelsMap.put("e320", "E320");
        modelsMap.put("e350", "E350");
        modelsMap.put("e400", "MBE400");
        modelsMap.put("e420", "E420");
        modelsMap.put("e430", "E430");
        modelsMap.put("e500", "E500");
        modelsMap.put("e55 amg", "E55AMG");
        modelsMap.put("e550", "E550");
        modelsMap.put("e63 amg", "E63AMG");
        modelsMap.put("g-class (4)", "G_CLASS");
        modelsMap.put("g500", "G500");
        modelsMap.put("g55 amg", "G55AMG");
        modelsMap.put("g550", "G550");
        modelsMap.put("g63 amg", "G63AMG");
        modelsMap.put("gl-class (5)", "GL_CLASS");
        modelsMap.put("gl320", "GL320BLUE");
        modelsMap.put("gl350", "GL350BLUE");
        modelsMap.put("gl450", "GL450");
        modelsMap.put("gl550", "GL550");
        modelsMap.put("gl63 amg", "GL63AMG");
        modelsMap.put("gla-class (2)", "GLA_CLASS");
        modelsMap.put("gla250", "MBGLA250");
        modelsMap.put("gla45 amg", "MBGLA45AMG");
        modelsMap.put("glc300", "MBGLC300");
        modelsMap.put("gle-class (6)", "GLE_CLASS");
        modelsMap.put("gle300d", "MBGLE300D");
        modelsMap.put("gle350", "MBGLE350");
        modelsMap.put("gle400", "MBGLE400");
        modelsMap.put("gle450", "MBGLE450");
        modelsMap.put("gle550e", "MBGLE550E");
        modelsMap.put("gle63 amg", "MBGLE63AMG");
        modelsMap.put("glk-class (2)", "GLK_CLASS");
        modelsMap.put("glk250", "GLK250BLUE");
        modelsMap.put("glk350", "GLK350");
        modelsMap.put("m-class (10)", "M_CLASS");
        modelsMap.put("ml250", "MBML250BLU");
        modelsMap.put("ml320", "ML320");
        modelsMap.put("ml350", "ML350");
        modelsMap.put("ml400", "MBML400");
        modelsMap.put("ml430", "ML430");
        modelsMap.put("ml450", "ML450HY");
        modelsMap.put("ml500", "ML500");
        modelsMap.put("ml55 amg", "ML55AMG");
        modelsMap.put("ml550", "ML550");
        modelsMap.put("ml63 amg", "ML63AMG");
        modelsMap.put("metris", "MBMETRIS");
        modelsMap.put("r-class (4)", "R_CLASS");
        modelsMap.put("r320", "R320BLUE");
        modelsMap.put("r350", "R350");
        modelsMap.put("r500", "R500");
        modelsMap.put("r63 amg", "R63AMG");
        modelsMap.put("s-class (12)", "S_CLASS");
        modelsMap.put("maybach s600", "MBMAYS600");
        modelsMap.put("s320", "S320");
        modelsMap.put("s350", "S350");
        modelsMap.put("s400", "S400HY");
        modelsMap.put("s420", "S420");
        modelsMap.put("s430", "S430");
        modelsMap.put("s500", "S500");
        modelsMap.put("s55 amg", "S55AMG");
        modelsMap.put("s550", "S550");
        modelsMap.put("s600", "S600");
        modelsMap.put("s63 amg", "S63AMG");
        modelsMap.put("s65 amg", "S65AMG");
        modelsMap.put("sl-class (8)", "SL_CLASS");
        modelsMap.put("sl320", "SL320");
        modelsMap.put("sl400", "MBSL400");
        modelsMap.put("sl500", "SL500");
        modelsMap.put("sl55 amg", "SL55AMG");
        modelsMap.put("sl550", "SL550");
        modelsMap.put("sl600", "SL600");
        modelsMap.put("sl63 amg", "SL63AMG");
        modelsMap.put("sl65 amg", "SL65AMG");
        modelsMap.put("slk-class (8)", "SLK_CLASS");
        modelsMap.put("slk230", "SLK230");
        modelsMap.put("slk250", "SLK250");
        modelsMap.put("slk280", "SLK280");
        modelsMap.put("slk300", "SLK300");
        modelsMap.put("slk32 amg", "SLK32AMG");
        modelsMap.put("slk320", "SLK320");
        modelsMap.put("slk350", "SLK350");
        modelsMap.put("slk55 amg", "SLK55AMG");
        modelsMap.put("slr", "SLR");
        modelsMap.put("sls amg", "SLSAMG");
        modelsMap.put("sprinter", "MBSPRINTER");
        modelsMap.put("other mercedes-benz models", "MBOTH");
        modelsMap.put("capri", "CAPRI");
        modelsMap.put("cougar", "COUGAR");
        modelsMap.put("grand marquis", "MERCGRAND");
        modelsMap.put("ln7", "LN7");
        modelsMap.put("lynx", "LYNX");
        modelsMap.put("marauder", "MARAUDER");
        modelsMap.put("mariner", "MARINER");
        modelsMap.put("marquis", "MARQ");
        modelsMap.put("milan", "MILAN");
        modelsMap.put("montego", "MONTEGO");
        modelsMap.put("monterey", "MONTEREY");
        modelsMap.put("mountaineer", "MOUNTA");
        modelsMap.put("mystique", "MYSTIQ");
        modelsMap.put("sable", "SABLE");
        modelsMap.put("topaz", "TOPAZ");
        modelsMap.put("tracer", "TRACER");
        modelsMap.put("villager", "VILLA");
        modelsMap.put("zephyr", "MERCZEP");
        modelsMap.put("other mercury models", "MEOTH");
        modelsMap.put("cooper", "COOPER");
        modelsMap.put("cooper clubman", "COOPERCLUB");
        modelsMap.put("cooper countryman", "COUNTRYMAN");
        modelsMap.put("cooper coupe", "MINICOUPE");
        modelsMap.put("cooper paceman", "MINIPACE");
        modelsMap.put("cooper roadster", "COOPERROAD");
        modelsMap.put("3000gt", "3000GT");
        modelsMap.put("cordia", "CORD");
        modelsMap.put("diamante", "DIAMAN");
        modelsMap.put("eclipse", "ECLIP");
        modelsMap.put("endeavor", "ENDEAVOR");
        modelsMap.put("expo", "MITEXP");
        modelsMap.put("galant", "GALANT");
        modelsMap.put("i", "MITI");
        modelsMap.put("lancer", "LANCERMITS");
        modelsMap.put("lancer evolution", "LANCEREVO");
        modelsMap.put("mighty max", "MITPU");
        modelsMap.put("mirage", "MIRAGE");
        modelsMap.put("montero", "MONT");
        modelsMap.put("montero sport", "MONTSPORT");
        modelsMap.put("outlander", "OUTLANDER");
        modelsMap.put("outlander sport", "OUTLANDSPT");
        modelsMap.put("precis", "PRECIS");
        modelsMap.put("raider", "RAIDERMITS");
        modelsMap.put("sigma", "SIGMA");
        modelsMap.put("starion", "MITSTAR");
        modelsMap.put("tredia", "TRED");
        modelsMap.put("van", "MITVAN");
        modelsMap.put("other mitsubishi models", "MITOTH");
        modelsMap.put("200sx", "NIS200SX");
        modelsMap.put("240sx", "240SX");
        modelsMap.put("300zx", "300ZXTURBO");
        modelsMap.put("350z", "350Z");
        modelsMap.put("370z", "370Z");
        modelsMap.put("altima", "ALTIMA");
        modelsMap.put("armada", "PATHARMADA");
        modelsMap.put("axxess", "AXXESS");
        modelsMap.put("cube", "CUBE");
        modelsMap.put("frontier", "FRONTI");
        modelsMap.put("gt-r", "GT-R");
        modelsMap.put("juke", "JUKE");
        modelsMap.put("leaf", "LEAF");
        modelsMap.put("maxima", "MAX");
        modelsMap.put("murano", "MURANO");
        modelsMap.put("murano crosscabriolet", "MURANOCROS");
        modelsMap.put("nv", "NV");
        modelsMap.put("nv200", "NISNV200");
        modelsMap.put("nx", "NX");
        modelsMap.put("pathfinder", "PATH");
        modelsMap.put("pickup", "NISPU");
        modelsMap.put("pulsar", "PULSAR");
        modelsMap.put("quest", "QUEST");
        modelsMap.put("rogue", "ROGUE");
        modelsMap.put("sentra", "SENTRA");
        modelsMap.put("stanza", "STANZA");
        modelsMap.put("titan", "TITAN");
        modelsMap.put("van", "NISVAN");
        modelsMap.put("versa", "VERSA");
        modelsMap.put("versa note", "NISVERSNOT");
        modelsMap.put("xterra", "XTERRA");
        modelsMap.put("other nissan models", "NISSOTH");
        modelsMap.put("88", "88");
        modelsMap.put("achieva", "ACHIEV");
        modelsMap.put("alero", "ALERO");
        modelsMap.put("aurora", "AURORA");
        modelsMap.put("bravada", "BRAV");
        modelsMap.put("custom cruiser", "CUCR");
        modelsMap.put("cutlass", "OLDCUS");
        modelsMap.put("cutlass calais", "OLDCALAIS");
        modelsMap.put("cutlass ciera", "CIERA");
        modelsMap.put("cutlass supreme", "CSUPR");
        modelsMap.put("firenza", "OLDSFIR");
        modelsMap.put("intrigue", "INTRIG");
        modelsMap.put("ninety-eight", "98");
        modelsMap.put("omega", "OMEG");
        modelsMap.put("regency", "REGEN");
        modelsMap.put("silhouette", "SILHO");
        modelsMap.put("toronado", "TORO");
        modelsMap.put("other oldsmobile models", "OLDOTH");
        modelsMap.put("acclaim", "ACC");
        modelsMap.put("arrow", "ARROW");
        modelsMap.put("breeze", "BREEZE");
        modelsMap.put("caravelle", "CARAVE");
        modelsMap.put("champ", "CHAMP");
        modelsMap.put("colt", "COLT");
        modelsMap.put("conquest", "PLYMCONQ");
        modelsMap.put("gran fury", "GRANFURY");
        modelsMap.put("grand voyager", "PLYMGRANV");
        modelsMap.put("horizon", "HORI");
        modelsMap.put("laser", "LASER");
        modelsMap.put("neon", "NEON");
        modelsMap.put("prowler", "PROWLE");
        modelsMap.put("reliant", "RELI");
        modelsMap.put("sapporo", "SAPPOROPLY");
        modelsMap.put("scamp", "SCAMP");
        modelsMap.put("sundance", "SUNDAN");
        modelsMap.put("trailduster", "TRAILDUST");
        modelsMap.put("turismo", "TURISMO");
        modelsMap.put("voyager", "VOYA");
        modelsMap.put("other plymouth models", "PLYOTH");
        modelsMap.put("1000", "T-1000");
        modelsMap.put("6000", "6000");
        modelsMap.put("aztek", "AZTEK");
        modelsMap.put("bonneville", "BON");
        modelsMap.put("catalina", "CATALINA");
        modelsMap.put("fiero", "FIERO");
        modelsMap.put("firebird", "FBIRD");
        modelsMap.put("g3", "G3");
        modelsMap.put("g5", "G5");
        modelsMap.put("g6", "G6");
        modelsMap.put("g8", "G8");
        modelsMap.put("grand am", "GRNDAM");
        modelsMap.put("grand prix", "GP");
        modelsMap.put("gto", "GTO");
        modelsMap.put("j2000", "J2000");
        modelsMap.put("le mans", "LEMANS");
        modelsMap.put("montana", "MONTANA");
        modelsMap.put("parisienne", "PARISI");
        modelsMap.put("phoenix", "PHOENIX");
        modelsMap.put("safari", "SAFARIPONT");
        modelsMap.put("solstice", "SOLSTICE");
        modelsMap.put("sunbird", "SUNBIR");
        modelsMap.put("sunfire", "SUNFIR");
        modelsMap.put("torrent", "TORRENT");
        modelsMap.put("trans sport", "TS");
        modelsMap.put("vibe", "VIBE");
        modelsMap.put("other pontiac models", "PONOTH");
        modelsMap.put("911", "911");
        modelsMap.put("918 spyder", "POR918SPYD");
        modelsMap.put("924", "924");
        modelsMap.put("928", "928");
        modelsMap.put("944", "944");
        modelsMap.put("968", "968");
        modelsMap.put("boxster", "BOXSTE");
        modelsMap.put("carrera gt", "CARRERAGT");
        modelsMap.put("cayenne", "CAYENNE");
        modelsMap.put("cayman", "CAYMAN");
        modelsMap.put("macan", "PORMACAN");
        modelsMap.put("panamera", "PANAMERA");
        modelsMap.put("other porsche models", "POROTH");
        modelsMap.put("1500", "RM1500");
        modelsMap.put("2500", "RM2500");
        modelsMap.put("3500", "RM3500");
        modelsMap.put("4500", "RM4500");
        modelsMap.put("5500", "RM5500");
        modelsMap.put("c/v", "RMCV");
        modelsMap.put("promaster", "RMPROMAST");
        modelsMap.put("promaster city", "RMPROCITY");
        modelsMap.put("camargue", "CAMAR");
        modelsMap.put("corniche", "CORN");
        modelsMap.put("ghost", "GHOST");
        modelsMap.put("park ward", "PARKWARD");
        modelsMap.put("phantom", "PHANT");
        modelsMap.put("silver dawn", "DAWN");
        modelsMap.put("silver seraph", "SILSERAPH");
        modelsMap.put("silver spirit", "RRSPIR");
        modelsMap.put("silver spur", "SPUR");
        modelsMap.put("wraith", "WRAI");
        modelsMap.put("other rolls-royce models", "RROTH");
        modelsMap.put("9-2x", "9-2X");
        modelsMap.put("9-3", "9-3");
        modelsMap.put("9-4x", "9-4X");
        modelsMap.put("9-5", "9-5");
        modelsMap.put("9-7x", "97X");
        modelsMap.put("900", "900");
        modelsMap.put("9000", "9000");
        modelsMap.put("other saab models", "SAOTH");
        modelsMap.put("astra", "ASTRA");
        modelsMap.put("aura", "AURA");
        modelsMap.put("ion", "ION");
        modelsMap.put("l-series", "SATLSE");
        modelsMap.put("outlook", "OUTLOOK");
        modelsMap.put("relay", "RELAY");
        modelsMap.put("s-series", "SATSSE");
        modelsMap.put("sky", "SKY");
        modelsMap.put("vue", "VUE");
        modelsMap.put("other saturn models", "SATOTH");
        modelsMap.put("fr-s", "SCIFRS");
        modelsMap.put("ia", "SCIIA");
        modelsMap.put("im", "SCIIM");
        modelsMap.put("iq", "IQ");
        modelsMap.put("tc", "TC");
        modelsMap.put("xa", "XA");
        modelsMap.put("xb", "XB");
        modelsMap.put("xd", "XD");
        modelsMap.put("fortwo", "FORTWO");
        modelsMap.put("other smart models", "SMOTH");
        modelsMap.put("viper", "SRTVIPER");
        modelsMap.put("baja", "BAJA");
        modelsMap.put("brat", "BRAT");
        modelsMap.put("brz", "SUBBRZ");
        modelsMap.put("forester", "FOREST");
        modelsMap.put("impreza", "IMPREZ");
        modelsMap.put("impreza wrx", "IMPWRX");
        modelsMap.put("justy", "JUSTY");
        modelsMap.put("l series", "SUBL");
        modelsMap.put("legacy", "LEGACY");
        modelsMap.put("loyale", "LOYALE");
        modelsMap.put("outback", "SUBOUTBK");
        modelsMap.put("svx", "SVX");
        modelsMap.put("tribeca", "B9TRIBECA");
        modelsMap.put("wrx", "SUBWRX");
        modelsMap.put("xt", "XT");
        modelsMap.put("xv crosstrek", "XVCRSSTREK");
        modelsMap.put("other subaru models", "SUBOTH");
        modelsMap.put("aerio", "AERIO");
        modelsMap.put("equator", "EQUATOR");
        modelsMap.put("esteem", "ESTEEM");
        modelsMap.put("forenza", "FORENZA");
        modelsMap.put("grand vitara", "GRANDV");
        modelsMap.put("kizashi", "KIZASHI");
        modelsMap.put("reno", "RENO");
        modelsMap.put("samurai", "SAMUR");
        modelsMap.put("sidekick", "SIDE");
        modelsMap.put("swift", "SWIFT");
        modelsMap.put("sx4", "SX4");
        modelsMap.put("verona", "VERONA");
        modelsMap.put("vitara", "VITARA");
        modelsMap.put("x-90", "X90");
        modelsMap.put("xl7", "XL7");
        modelsMap.put("other suzuki models", "SUZOTH");
        modelsMap.put("model s", "TESMODS");
        modelsMap.put("roadster", "ROADSTER");
        modelsMap.put("4runner", "4RUN");
        modelsMap.put("avalon", "AVALON");
        modelsMap.put("camry", "CAMRY");
        modelsMap.put("celica", "CELICA");
        modelsMap.put("corolla", "COROL");
        modelsMap.put("corona", "CORONA");
        modelsMap.put("cressida", "CRESS");
        modelsMap.put("echo", "ECHO");
        modelsMap.put("fj cruiser", "FJCRUIS");
        modelsMap.put("highlander", "HIGHLANDER");
        modelsMap.put("land cruiser", "LC");
        modelsMap.put("matrix", "MATRIX");
        modelsMap.put("mr2", "MR2");
        modelsMap.put("mr2 spyder", "MR2SPYDR");
        modelsMap.put("paseo", "PASEO");
        modelsMap.put("pickup", "PICKUP");
        modelsMap.put("previa", "PREVIA");
        modelsMap.put("prius", "PRIUS");
        modelsMap.put("prius c", "PRIUSC");
        modelsMap.put("prius v", "PRIUSV");
        modelsMap.put("rav4", "RAV4");
        modelsMap.put("sequoia", "SEQUOIA");
        modelsMap.put("sienna", "SIENNA");
        modelsMap.put("solara", "SOLARA");
        modelsMap.put("starlet", "STARLET");
        modelsMap.put("supra", "SUPRA");
        modelsMap.put("t100", "T100");
        modelsMap.put("tacoma", "TACOMA");
        modelsMap.put("tercel", "TERCEL");
        modelsMap.put("tundra", "TUNDRA");
        modelsMap.put("van", "TOYVAN");
        modelsMap.put("venza", "VENZA");
        modelsMap.put("yaris", "YARIS");
        modelsMap.put("other toyota models", "TOYOTH");
        modelsMap.put("beetle", "BEETLE");
        modelsMap.put("cabrio", "VOLKSCAB");
        modelsMap.put("cabriolet", "CAB");
        modelsMap.put("cc", "CC");
        modelsMap.put("corrado", "CORR");
        modelsMap.put("dasher", "DASHER");
        modelsMap.put("e-golf", "VOLKSEGOLF");
        modelsMap.put("eos", "EOS");
        modelsMap.put("eurovan", "EUROVAN");
        modelsMap.put("fox", "VOLKSFOX");
        modelsMap.put("gli", "GLI");
        modelsMap.put("golf r", "GOLFR");
        modelsMap.put("gti", "GTI");
        modelsMap.put("golf and rabbit models (2)", "GOLFANDRABBITMODELS");
        modelsMap.put("golf", "GOLF");
        modelsMap.put("rabbit", "RABBIT");
        modelsMap.put("jetta", "JET");
        modelsMap.put("passat", "PASS");
        modelsMap.put("phaeton", "PHAETON");
        modelsMap.put("pickup", "RABBITPU");
        modelsMap.put("quantum", "QUAN");
        modelsMap.put("r32", "R32");
        modelsMap.put("routan", "ROUTAN");
        modelsMap.put("scirocco", "SCIR");
        modelsMap.put("tiguan", "TIGUAN");
        modelsMap.put("touareg", "TOUAREG");
        modelsMap.put("vanagon", "VANAG");
        modelsMap.put("other volkswagen models", "VWOTH");
        modelsMap.put("240", "240");
        modelsMap.put("260", "260");
        modelsMap.put("740", "740");
        modelsMap.put("760", "760");
        modelsMap.put("780", "780");
        modelsMap.put("850", "850");
        modelsMap.put("940", "940");
        modelsMap.put("960", "960");
        modelsMap.put("c30", "C30");
        modelsMap.put("c70", "C70");
        modelsMap.put("s40", "S40");
        modelsMap.put("s60", "S60");
        modelsMap.put("s70", "S70");
        modelsMap.put("s80", "S80");
        modelsMap.put("s90", "S90");
        modelsMap.put("v40", "V40");
        modelsMap.put("v50", "V50");
        modelsMap.put("v60", "VOLVOV60");
        modelsMap.put("v70", "V70");
        modelsMap.put("v90", "V90");
        modelsMap.put("xc60", "XC60");
        modelsMap.put("xc70", "XC");
        modelsMap.put("xc90", "XC90");
        modelsMap.put("other volvo models", "VOLOTH");


    }

    public static String getMakeIdByName(String name) {
        return makesMap.get(name.toLowerCase());
    }

    public static String getModelIdByName(String name) {
        return modelsMap.get(name.toLowerCase());
    }

    public static Set<String> getMakesNames() {
        return makesMap.keySet();
    }

    public static Set<String> getModelNames() {
        return modelsMap.keySet();
    }
}
